  export const teams = [
    {
      id: "juv",
      name: "Juventus",
      abbr: "JUV",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "psv",
      name: "PSV Eindhoven",
      abbr: "PSV",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "ars",
      name: "Arsenal",
      abbr: "ARS",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "rma",
      name: "Real Madrid",
      abbr: "RMA",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "mci",
      name: "Manchester City",
      abbr: "MCI",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "atm",
      name: "Atletico Madrid",
      abbr: "ATM",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "ben",
      name: "Benfica",
      abbr: "BEN",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "bar",
      name: "Barcelona",
      abbr: "BAR",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "asm",
      name: "AS Monaco",
      abbr: "ASM",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "bvb",
      name: "Borussia Dortmund",
      abbr: "BVB",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "lil",
      name: "Lille",
      abbr: "LIL",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "scp",
      name: "Sporting CP",
      abbr: "SCP",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "red",
      name: "Red Star",
      abbr: "RED",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "psg",
      name: "Paris Saint-Germain",
      abbr: "PSG",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "liv",
      name: "Liverpool",
      abbr: "LIV",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "int",
      name: "Inter Milan",
      abbr: "INT",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "fcb",
      name: "Bayern Munich",
      abbr: "FCB",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "bor",
      name: "Bordeaux",
      abbr: "BOR",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "cel",
      name: "Celtic",
      abbr: "CEL",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "clb",
      name: "Club Brugge",
      abbr: "CLB",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "ata",
      name: "Atalanta",
      abbr: "ATA",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "avl",
      name: "Aston Villa",
      abbr: "AVL",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "fey",
      name: "Feyenoord",
      abbr: "FEY",
      logo: "/mig/icons/Asset 1.png",
    },
    {
      id: "mil",
      name: "AC Milan",
      abbr: "MIL",
      logo: "/mig/icons/Asset 1.png",
    },
  ];


  
  export const matches = [
    {
      id: "m1",
      round: 1,
      position: 1,
      team1: teams[0],
      team2: teams[1],
      score1: 3,
      score2: 4,
      nextMatchId: "m13",
      connectorIds: ["c1"],
    },
    {
      id: "m2",
      round: 1,
      position: 2,
      team1: teams[4],
      team2: teams[3],
      score1: 3,
      score2: 6,
      nextMatchId: "m13",
      connectorIds: ["c1"],
    },
    {
      id: "m3",
      round: 1,
      position: 3,
      team1: teams[19],
      team2: teams[20],
      score1: 5,
      score2: 2,
      nextMatchId: "m14",
      connectorIds: ["c2"],
    },
    {
      id: "m4",
      round: 1,
      position: 4,
      team1: teams[21],
      team2: teams[21],
      score1: 1,
      score2: 0,
      nextMatchId: "m14",
      connectorIds: ["c2"],
    },

    // Round 1 - Right side
    {
      id: "m5",
      round: 1,
      position: 5,
      team1: teams[6],
      team2: teams[7],
      score1: 1,
      score2: 4,
      nextMatchId: "m17",
      connectorIds: ["c3"],
    },
    {
      id: "m6",
      round: 1,
      position: 6,
      team1: teams[8],
      team2: teams[6],
      score1: 3,
      score2: 4,
      nextMatchId: "m17",
      connectorIds: ["c3"],
    },
    {
      id: "m7",
      round: 1,
      position: 7,
      team1: teams[9],
      team2: teams[10],
      score1: 3,
      score2: 2,
      nextMatchId: "m18",
      connectorIds: ["c4"],
    },
    {
      id: "m8",
      round: 1,
      position: 8,
      team1: teams[11],
      team2: teams[9],
      score1: 0,
      score2: 3,
      nextMatchId: "m18",
      connectorIds: ["c4"],
    },
    {
      id: "m9",
      round: 1,
      position: 9,
      team1: teams[16],
      team2: teams[17],
      score1: 5,
      score2: 0,
      nextMatchId: "m19",
      connectorIds: ["c5"],
    },
    {
      id: "m10",
      round: 1,
      position: 10,
      team1: teams[18],
      team2: teams[16],
      score1: 2,
      score2: 3,
      nextMatchId: "m19",
      connectorIds: ["c5"],
    },
    {
      id: "m11",
      round: 1,
      position: 11,
      team1: teams[22],
      team2: teams[15],
      score1: 1,
      score2: 4,
      nextMatchId: "m20",
      connectorIds: ["c6"],
    },
    {
      id: "m12",
      round: 1,
      position: 12,
      team1: teams[22],
      team2: teams[23],
      score1: 2,
      score2: 1,
      nextMatchId: "m20",
      connectorIds: ["c6"],
    },

    // Round 2 - Left side
    {
      id: "m13",
      round: 2,
      position: 1,
      team1: teams[1],
      team2: teams[2],
      score1: 3,
      score2: 9,
      nextMatchId: "m19",
      connectorIds: ["c1", "c7"],
    },
    {
      id: "m14",
      round: 2,
      position: 2,
      team1: teams[3],
      team2: teams[20],
      score1: 2,
      score2: 2,
      winner: "rma",
      nextMatchId: "m19",
      connectorIds: ["c2", "c7"],
    },
    {
      id: "m15",
      round: 2,
      position: 3,
      team1: teams[13],
      team2: teams[14],
      score1: 1,
      score2: 1,
      winner: "psg",
      nextMatchId: "m20",
      connectorIds: ["c8"],
    },
    {
      id: "m16",
      round: 2,
      position: 4,
      team1: teams[19],
      team2: teams[21],
      score1: 1,
      score2: 0,
      nextMatchId: "m20",
      connectorIds: ["c8"],
    },

    // Round 2 - Right side
    {
      id: "m17",
      round: 2,
      position: 5,
      team1: teams[7],
      team2: teams[9],
      score1: 5,
      score2: 3,
      nextMatchId: "m21",
      connectorIds: ["c3", "c9"],
    },
    {
      id: "m18",
      round: 2,
      position: 6,
      team1: teams[16],
      team2: teams[15],
      score1: 3,
      score2: 4,
      nextMatchId: "m21",
      connectorIds: ["c4", "c9"],
    },

    // Round 3 - Left side
    {
      id: "m19",
      round: 3,
      position: 1,
      team1: teams[2],
      team2: teams[3],
      score1: 5,
      score2: 1,
      nextMatchId: "m22",
      connectorIds: ["c7", "c10"],
    },
    {
      id: "m20",
      round: 3,
      position: 2,
      team1: teams[13],
      team2: teams[21],
      score1: 5,
      score2: 4,
      nextMatchId: "m22",
      connectorIds: ["c8", "c10"],
    },

    // Round 3 - Right side
    {
      id: "m21",
      round: 3,
      position: 3,
      team1: teams[7],
      team2: teams[15],
      score1: 6,
      score2: 7,
      nextMatchId: "m23",
      connectorIds: ["c9", "c11"],
    },

    // Semi-finals
    {
      id: "m22",
      round: 4,
      position: 1,
      team1: teams[2],
      team2: teams[13],
      score1: 1,
      score2: 3,
      nextMatchId: "m23",
      connectorIds: ["c10", "c12"],
    },
    {
      id: "m23",
      round: 4,
      position: 2,
      team1: teams[13],
      team2: teams[15],
      score1: 0,
      score2: 0,
      date: "May 31",
      label: "FINAL",
      connectorIds: ["c11", "c12"],
    },
  ];